
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[495] =
    {   0,
        0,    0,   37,   36,    1,    2,    1,   36,   35,    4,
        5,    3,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,    1,    1,   35,    0,    6,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   34,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,    7,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,    8,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   31,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   22,   35,   35,
       35,   35,   35,   18,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   24,
       23,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,    9,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   15,   35,   25,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   17,   35,
       35,   35,   35,   11,   35,   35,   35,   35,   35,   35,
       35,   13,   35,   35,   35,   35,   27,   20,   35,   35,
       35,   29,   35,   35,   35,   14,   12,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   16,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   10,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   30,   35,   35,   35,
       35,   28,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   32,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   21,   26,   19,   35,   35,
       35,   35,   33,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    1,    1,    9,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   10,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   11,   15,
       11,   16,   17,   18,   11,   19,   20,   21,   22,   11,
       11,   23,   24,   25,   11,   11,   26,   11,   27,   11,
        1,    1,    1,    1,    1,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   11,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    1,    2,    1,    2,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    } ;

static const flex_int16_t yy_base[497] =
    {   0,
        0,    0, 1015, 1023,   51, 1023,   52, 1009, 1011, 1023,
     1023, 1010,   55,   56,   57,   58,   59,   60,   61,   63,
       64,   66,   71,   67,   73,   74,   68,   79,   76,   78,
       72,   86,   84,   88,   75,   81, 1009, 1005, 1023,   80,
       85,   92,   87,   97,  119,  121,   65,  122,  126,  127,
      128,  135,  132,  136,  139,  140,  142,  143,  144,  145,
      147, 1007,  150,  146,  148,  149,  151,  152,  153,  155,
      154,  160,  157,  161,  169,  166,  171,  167,  158,  176,
      164,  178,  177,  181,  183,  184,  185,  198,  203,  205,
      208,  211,  212,  214,  215,  216,  217,  259,  218,  219,

      223,  224,  220,  225,  228,  229,  231,  238,  243,  250,
      233,  234,  244,  253,  251,  260,  254,  255,  263,  270,
      257,  271,  267,  272,  273,  274,  282,  283,  284,  277,
      291,  279,  293,  294,  299,  296,  305,  328,  295,  288,
      285,  306,  301,  314,  319,  324,  327,  333,  336,  337,
      338,  340,  341,  342,  343,  345,  346,  347,  349,  350,
      352,  354,  355,  356,  360,  359,  361,  362,  363,  369,
      370,  377,  382,  374,  384,  398,  364,  395,  367,  405,
      383,  388,  389,  396,  411,  401,  412,  413,  414,  415,
      416,  417, 1006,  418,  420,  423,  425,  424,  428,  429,

      430,  432,  435,  433,  439,  440,  444,  445,  438,  446,
      449,  441, 1005,  452,  456,  442,  451,  448,  459,  455,
      447,  462,  489,  492,  469,  496,  480, 1004,  483,  484,
      493,  499,  488, 1003,  500,  501,  502,  504,  505,  506,
      507,  510,  511,  514,  515,  516,  517,  520,  518, 1002,
     1000,  519,  523,  529,  524,  532,  533,  525,  535,  536,
      537,  549,  538,  552,  542,  551,  539,  555,  557,  999,
      558,  569,  562,  565,  570,  571,  584,  566,  561,  573,
      580,  583,  587,  588,  592,  593,  598,  599,  597,  601,
      602,  605,  604,  608,  607,  609,  610,  612,  614,  617,

      615,  618,  620,  622,  625,  621,  629,  631,  633,  636,
      637,  638,  639,  641,  642,  644,  647,  648,  649,  658,
      650,  659,  660,  664,  665,  998,  666,  997,  672,  674,
      677,  669,  679,  681,  687,  688,  675,  682,  683,  670,
      694,  697,  702,  703,  708,  711,  714,  715,  716,  719,
      720,  722,  721,  723,  724,  726,  725,  731,  996,  730,
      732,  733,  735,  995,  734,  740,  741,  743,  744,  746,
      749,  994,  747,  750,  751,  752,  992,  990,  760,  771,
      757,  988,  754,  772,  774,  987,  986,  779,  780,  791,
      781,  785,  788,  792,  794,  795,  796,  799,  800,  801,

      802,  803,  805,  806,  808,  809,  813,  816,  812,  818,
      819,  820,  823,  821,  825,  826,  839,  828,  831,  832,
      835,  836,  842,  847,  848,  843,  851,  852,  985,  858,
      859,  868,  861,  862,  865,  871,  873,  875,  984,  880,
      878,  881,  879,  883,  884,  885,  887,  888,  891,  892,
      894,  893,  907,  895,  899,  896,  983,  908,  914,  900,
      915,  982,  916,  917,  918,  919,  924,  920,  929,  927,
      933,  932,  980,  935,  937,  938,  941,  945,  944,  946,
      952,  951,  947,  956,  953,  978,  976,  973,  958,  965,
      969,  971,  972, 1023,   70, 1020

    } ;

static const flex_int16_t yy_def[497] =
    {   0,
      494,    1,  494,  494,  494,  494,  495,  496,  495,  494,
      494,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  494,  495,  495,  496,  494,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,    0,  494,  494

    } ;

static const flex_int16_t yy_nxt[1076] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    9,
        9,   13,   14,    9,   15,    9,   16,    9,   17,   18,
        9,   19,   20,   21,   22,   23,   24,    9,    9,    9,
        9,   25,   26,    9,    9,   27,    9,   28,   29,   30,
       31,    9,    9,    9,   32,   33,    9,    9,    9,    9,
        9,   34,   35,   35,   35,   36,  494,  494,  494,  494,
      494,  494,  494,   45,  494,  494,  494,  494,  494,  494,
       79,   37,  494,  494,  494,  494,   35,  494,   35,  494,
      494,  494,   35,   42,   36,  494,  494,  494,  494,  494,
       46,   49,   40,  494,   51,   50,   43,   44,  494,   48,

       53,   41,   55,   47,   52,   56,   54,   57,   58,   60,
       63,   66,   62,   65,   61,   59,   64,   67,   69,   71,
      494,   68,  494,  494,   78,   75,   72,  494,  494,  494,
       73,   74,   70,  494,   76,   82,  494,  494,   84,   86,
      494,  494,   87,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,   77,  494,  494,
      103,  494,  494,   85,   81,  494,  104,  494,  494,   80,
      494,   88,  494,   83,  107,   89,   91,  494,  494,  494,
       98,  112,  494,  108,  494,  494,  494,   97,   90,   96,
       92,  102,   93,   94,   95,   98,  100,  101,   99,  494,

      105,   98,  109,  106,  494,  111,  494,  110,  121,  494,
      122,  114,  494,  494,  118,  494,  494,  494,  494,  494,
      494,  494,  115,  113,  494,  494,  494,  136,  117,  494,
      494,  139,  494,  116,  494,  494,  137,  119,  124,  494,
      120,  142,  123,   98,  494,  494,  143,  126,   98,  134,
      135,  494,  494,  144,  494,  494,  494,   98,  494,  125,
      494,  494,  141,   98,  494,  150,  153,  145,  494,  140,
      138,  494,  494,  494,  494,  494,  158,  159,  494,  146,
      494,  151,  152,  494,  494,  494,  494,  147,  149,  494,
      127,  128,  494,  148,  494,  494,  494,  494,  129,  130,

      494,  154,  494,  131,  132,  155,  494,  494,  161,  157,
      133,  160,   98,   69,  156,  494,   66,   58,   60,   65,
      494,  167,   67,   61,   71,  494,   68,   70,  494,  494,
       98,  162,  165,   98,  494,  166,  164,  494,  494,  494,
      163,  494,  494,  494,  494,  178,  494,  494,  494,  181,
      494,  494,  168,  494,  169,  494,  494,  494,  170,  188,
      494,  494,  494,  494,  494,  494,  171,  173,  494,  186,
      494,  494,  172,  195,  179,  494,  180,  184,  494,  176,
      174,  185,  196,  494,  494,  494,  190,  199,  175,  494,
      494,  177,  182,  192,  183,  189,  494,  494,  187,  494,

      194,  191,  494,  200,  201,  198,  494,  193,  204,  197,
      203,  202,  494,  494,  494,  494,  494,  494,  494,  494,
      216,  494,  206,  207,  494,  494,  494,  221,  205,  494,
      494,  494,  210,  494,  494,  225,  494,  212,  209,  494,
      494,  494,  494,  494,  208,  494,  494,  494,  494,  494,
      494,  213,  494,  494,  214,  236,  494,  494,  211,  237,
      494,  217,  241,  494,  215,  218,  226,  229,  219,  220,
      494,  230,  231,  222,  223,  235,  224,  232,  227,  228,
      234,  494,  239,  233,  494,  494,  242,  238,  240,  494,
      494,  243,  245,  494,  494,  246,  244,  494,  247,  248,

      494,  494,  494,  494,  253,  494,  494,  494,  494,  260,
      259,  494,  494,  262,  249,  494,  494,  494,  494,  494,
      494,  494,  250,  251,  494,  494,  494,  255,  252,  254,
      494,  256,  272,  494,  494,  258,  494,  494,  494,  494,
      494,  281,  257,  494,  267,  264,  266,  268,  265,  269,
      494,  263,  494,  494,  270,  282,  494,  261,  494,  494,
      287,  288,  494,  494,  276,  290,  494,  494,  271,  273,
      494,  494,  494,  292,  494,  274,  275,  279,  285,  277,
      278,  494,  283,  289,  494,  494,  280,  294,  494,  494,
      300,  284,  286,  494,  494,  302,  291,  295,  494,  494,

      494,  293,  494,  494,  297,  494,  494,  296,  494,  494,
      494,  494,  313,  494,  307,  494,  494,  298,  494,  494,
      318,  494,  494,  494,  306,  309,  494,  301,  304,  308,
      494,  299,  494,  305,  494,  310,  311,  494,  494,  494,
      494,  303,  494,  494,  332,  494,  312,  321,  494,  494,
      494,  494,  315,  322,  316,  314,  323,  317,  324,  494,
      494,  494,  319,  320,  327,  494,  494,  494,  330,  326,
      494,  494,  325,  494,  329,  494,  494,  331,  494,  328,
      494,  333,  494,  494,  494,  338,  335,  334,  494,  494,
      352,  353,  339,  336,  337,  494,  344,  342,  494,  346,

      340,  343,  354,  494,  494,  347,  341,  349,  348,  494,
      350,  351,  494,  345,  357,  494,  494,  494,  356,  355,
      494,  494,  494,  494,  494,  494,  494,  494,  374,  358,
      361,  494,  494,  494,  494,  494,  494,  360,  359,  362,
      363,  494,  494,  381,  494,  494,  383,  494,  494,  370,
      494,  494,  494,  494,  389,  494,  367,  364,  494,  365,
      372,  494,  371,  391,  368,  373,  366,  369,  375,  376,
      377,  379,  494,  494,  392,  494,  378,  385,  380,  386,
      494,  494,  494,  387,  384,  390,  494,  393,  394,  494,
      388,  382,  494,  494,  399,  494,  494,  494,  400,  406,

      494,  494,  494,  494,  494,  395,  494,  494,  412,  494,
      494,  396,  401,  494,  494,  398,  416,  494,  397,  494,
      494,  494,  494,  403,  494,  404,  494,  494,  409,  494,
      405,  402,  494,  494,  411,  408,  494,  494,  407,  414,
      494,  418,  426,  494,  494,  410,  420,  415,  494,  494,
      433,  413,  494,  494,  436,  417,  425,  422,  419,  494,
      494,  435,  494,  494,  427,  421,  494,  431,  423,  494,
      429,  440,  494,  432,  494,  424,  494,  428,  430,  494,
      494,  494,  494,  434,  494,  494,  494,  452,  494,  494,
      454,  437,  494,  494,  494,  494,  494,  494,  444,  441,

      494,  494,  439,  445,  438,  443,  442,  447,  494,  494,
      460,  464,  446,  448,  449,  494,  494,  494,  494,  494,
      494,  494,  451,  457,  458,  494,  450,  455,  494,  462,
      494,  463,  466,  494,  494,  453,  494,  456,  494,  494,
      479,  459,  494,  461,  481,  494,  494,  494,  494,  465,
      471,  473,  494,  494,  494,  467,  489,  494,  469,  494,
      468,  475,  477,  470,  476,  488,  494,  472,  485,  474,
      494,  478,  494,  494,  494,  480,  482,  494,  487,  494,
      493,  494,  483,  494,  494,  494,  494,  494,  494,  494,
      484,  494,  491,  494,  486,  494,  494,  494,  494,  494,

      494,  494,  490,  494,  494,  494,  494,  494,  494,   39,
      494,  494,  494,   39,  494,  494,  494,  494,  494,  492,
       38,   38,    3,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494
    } ;

static const flex_int16_t yy_chk[1076] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    7,    5,    7,   13,   14,   15,   16,
       17,   18,   19,   16,   20,   21,   47,   22,   24,   27,
       47,  495,   23,   31,   25,   26,   35,   29,   35,   30,
       28,   40,   36,   14,   36,   33,   41,   32,   43,   34,
       16,   18,   13,   42,   20,   19,   14,   15,   44,   17,

       22,   13,   23,   16,   21,   23,   22,   24,   25,   26,
       28,   31,   27,   30,   26,   25,   29,   32,   33,   34,
       45,   32,   46,   48,   46,   43,   40,   49,   50,   51,
       41,   42,   33,   53,   44,   50,   52,   54,   52,   54,
       55,   56,   55,   57,   58,   59,   60,   64,   61,   65,
       66,   63,   67,   68,   69,   71,   70,   45,   73,   79,
       73,   72,   74,   53,   49,   81,   74,   76,   78,   48,
       75,   56,   77,   51,   77,   56,   58,   80,   83,   82,
       66,   82,   84,   78,   85,   86,   87,   65,   57,   64,
       59,   72,   60,   61,   63,   70,   69,   71,   67,   88,

       75,   68,   79,   76,   89,   81,   90,   80,   90,   91,
       90,   84,   92,   93,   87,   94,   95,   96,   97,   99,
      100,  103,   84,   83,  101,  102,  104,  102,   86,  105,
      106,  105,  107,   85,  111,  112,  103,   88,   92,  108,
       89,  108,   91,   93,  109,  113,  109,   96,   97,   99,
      100,  110,  115,  110,  114,  117,  118,   94,  121,   95,
       98,  116,  107,  101,  119,  116,  119,  111,  123,  106,
      104,  120,  122,  124,  125,  126,  125,  126,  130,  112,
      132,  117,  118,  127,  128,  129,  141,  113,  115,  140,
       98,   98,  131,  114,  133,  134,  139,  136,   98,   98,

      135,  120,  143,   98,   98,  121,  137,  142,  137,  124,
       98,  136,  123,  132,  122,  144,  130,  127,  128,  129,
      145,  143,  131,  128,  133,  146,  131,  132,  147,  138,
      135,  138,  141,  134,  148,  142,  140,  149,  150,  151,
      139,  152,  153,  154,  155,  154,  156,  157,  158,  157,
      159,  160,  144,  161,  145,  162,  163,  164,  146,  164,
      166,  165,  167,  168,  169,  177,  147,  149,  179,  162,
      170,  171,  148,  171,  155,  174,  156,  160,  172,  152,
      150,  161,  172,  173,  181,  175,  166,  175,  151,  182,
      183,  153,  158,  168,  159,  165,  178,  184,  163,  176,

      170,  167,  186,  176,  177,  174,  180,  169,  180,  173,
      179,  178,  185,  187,  188,  189,  190,  191,  192,  194,
      192,  195,  182,  183,  196,  198,  197,  198,  181,  199,
      200,  201,  186,  202,  204,  202,  203,  188,  185,  209,
      205,  206,  212,  216,  184,  207,  208,  210,  221,  218,
      211,  189,  217,  214,  190,  214,  220,  215,  187,  215,
      219,  194,  219,  222,  191,  195,  203,  206,  196,  197,
      225,  207,  208,  199,  200,  212,  201,  209,  204,  205,
      211,  227,  217,  210,  229,  230,  220,  216,  218,  233,
      223,  221,  223,  224,  231,  224,  222,  226,  225,  226,

      232,  235,  236,  237,  232,  238,  239,  240,  241,  240,
      239,  242,  243,  242,  227,  244,  245,  246,  247,  249,
      252,  248,  229,  230,  253,  255,  258,  235,  231,  233,
      254,  236,  254,  256,  257,  238,  259,  260,  261,  263,
      267,  263,  237,  265,  247,  244,  246,  248,  245,  249,
      262,  243,  266,  264,  252,  264,  268,  241,  269,  271,
      269,  271,  279,  273,  258,  273,  274,  278,  253,  255,
      272,  275,  276,  275,  280,  256,  257,  261,  267,  259,
      260,  281,  265,  272,  282,  277,  262,  277,  283,  284,
      283,  266,  268,  285,  286,  285,  274,  278,  289,  287,

      288,  276,  290,  291,  280,  293,  292,  279,  295,  294,
      296,  297,  296,  298,  290,  299,  301,  281,  300,  302,
      301,  303,  306,  304,  289,  292,  305,  284,  287,  291,
      307,  282,  308,  288,  309,  293,  294,  310,  311,  312,
      313,  286,  314,  315,  314,  316,  295,  303,  317,  318,
      319,  321,  298,  304,  299,  297,  305,  300,  306,  320,
      322,  323,  302,  302,  309,  324,  325,  327,  312,  308,
      332,  340,  307,  329,  311,  330,  337,  313,  331,  310,
      333,  315,  334,  338,  339,  320,  317,  316,  335,  336,
      335,  336,  320,  318,  319,  341,  325,  323,  342,  329,

      321,  324,  337,  343,  344,  330,  322,  332,  331,  345,
      333,  334,  346,  327,  340,  347,  348,  349,  339,  338,
      350,  351,  353,  352,  354,  355,  357,  356,  357,  341,
      344,  360,  358,  361,  362,  365,  363,  343,  342,  345,
      346,  366,  367,  366,  368,  369,  368,  370,  373,  353,
      371,  374,  375,  376,  375,  383,  350,  347,  381,  348,
      355,  379,  354,  379,  351,  356,  349,  352,  358,  360,
      361,  363,  380,  384,  380,  385,  362,  370,  365,  371,
      388,  389,  391,  373,  369,  376,  392,  381,  383,  393,
      374,  367,  390,  394,  390,  395,  396,  397,  391,  397,

      398,  399,  400,  401,  402,  384,  403,  404,  403,  405,
      406,  385,  392,  409,  407,  389,  407,  408,  388,  410,
      411,  412,  414,  394,  413,  395,  415,  416,  400,  418,
      396,  393,  419,  420,  402,  399,  421,  422,  398,  405,
      417,  409,  417,  423,  426,  401,  411,  406,  424,  425,
      424,  404,  427,  428,  427,  408,  416,  413,  410,  430,
      431,  426,  433,  434,  418,  412,  435,  422,  414,  432,
      420,  432,  436,  423,  437,  415,  438,  419,  421,  441,
      443,  440,  442,  425,  444,  445,  446,  445,  447,  448,
      447,  428,  449,  450,  452,  451,  454,  456,  436,  433,

      455,  460,  431,  437,  430,  435,  434,  440,  453,  458,
      453,  458,  438,  441,  442,  459,  461,  463,  464,  465,
      466,  468,  444,  450,  451,  467,  443,  448,  470,  455,
      469,  456,  460,  472,  471,  446,  474,  449,  475,  476,
      475,  452,  477,  454,  477,  479,  478,  480,  483,  459,
      466,  468,  482,  481,  485,  461,  485,  484,  464,  489,
      463,  470,  472,  465,  471,  484,  490,  467,  481,  469,
      491,  474,  492,  493,  488,  476,  478,  487,  483,  486,
      492,  473,  479,  462,  457,  439,  429,  387,  386,  382,
      480,  378,  490,  377,  482,  372,  364,  359,  328,  326,

      270,  251,  489,  250,  234,  228,  213,  193,   62,   38,
       37,   12,    9,    8,    3,    0,    0,    0,    0,  491,
      496,  496,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "rockabilly.l"
#line 2 "rockabilly.l"
#include "rockabilly.tab.h"
#include <string.h>

// Function to map number words to their corresponding integer values
int word_to_num(const char *word) {
  if (strcmp(word, "zero") == 0) return 0;
  if (strcmp(word, "one") == 0) return 1;
  if (strcmp(word, "two") == 0) return 2;
  if (strcmp(word, "three") == 0) return 3;
  if (strcmp(word, "four") == 0) return 4;
  if (strcmp(word, "five") == 0) return 5;
  if (strcmp(word, "six") == 0) return 6;
  if (strcmp(word, "seven") == 0) return 7;
  if (strcmp(word, "eight") == 0) return 8;
  if (strcmp(word, "nine") == 0) return 9;
  return -1; // Invalid number word
}

// Function to convert a sequence of number words to an integer
int words_to_number(const char *words) {
  int num = 0;
  char word[10];
  const char *p = words;
  while (*p != '\0') {
    if (sscanf(p, "%s", word) == 1) {
      num = num * 10 + word_to_num(word);
      p += strlen(word);
      while (*p == ' ') p++;
    } else {
      break;
    }
  }
  return num;
}

#line 878 "lex.yy.c"
#line 879 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "rockabilly.l"


#line 1099 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 495 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1023 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "rockabilly.l"
;  // Ignore whitespaces
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 42 "rockabilly.l"
{ printf("Token: EOL\n"); return EOL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "rockabilly.l"
{ printf("Token: COMMA\n"); return COMMA; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "rockabilly.l"
{ printf("Token: RPAREN\n"); return RPAREN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "rockabilly.l"
{ printf("Token: LPAREN\n"); return LPAREN; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 46 "rockabilly.l"
{
  // Remove the quotes from the string and store in yylval
  yylval.sval = strdup(yytext + 1);
  yylval.sval[strlen(yylval.sval) - 1] = '\0';
  printf("Token: STRING, Value: %s\n", yylval.sval);
  return STRING;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "rockabilly.l"
{
  // Convert the sequence of number words to an integer and store in yylval
  yylval.ival = words_to_number(yytext);
  printf("Token: NUMBER, Value: %d\n", yylval.ival);
  return NUMBER;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "rockabilly.l"
{ printf("Token: LOCAL\n"); return LOCAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "rockabilly.l"
{ printf("Token: FUNCTION\n"); return FUNCTION; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "rockabilly.l"
{ printf("Token: END\n"); return END; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "rockabilly.l"
{ printf("Token: RETURN\n"); return RETURN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "rockabilly.l"
{ printf("Token: WHILE\n"); return WHILE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "rockabilly.l"
{ printf("Token: DO\n"); return DO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "rockabilly.l"
{ printf("Token: END\n"); return END; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "rockabilly.l"
{ printf("Token: IF\n"); return IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "rockabilly.l"
{ printf("Token: THEN\n"); return THEN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "rockabilly.l"
{ printf("Token: ELSE\n"); return ELSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "rockabilly.l"
{ printf("Token: END\n"); return END; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "rockabilly.l"
{ printf("Token: PRINT\n"); return PRINT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "rockabilly.l"
{ printf("Token: OR\n"); return OR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "rockabilly.l"
{ printf("Token: AND\n"); return AND; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "rockabilly.l"
{ printf("Token: EQ\n"); return EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "rockabilly.l"
{ printf("Token: GT\n"); return GT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "rockabilly.l"
{ printf("Token: LT\n"); return LT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "rockabilly.l"
{ printf("Token: PLUS\n"); return PLUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "rockabilly.l"
{ printf("Token: MINUS\n"); return MINUS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "rockabilly.l"
{ printf("Token: CONCAT\n"); return CONCAT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "rockabilly.l"
{ printf("Token: MUL\n"); return MUL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "rockabilly.l"
{ printf("Token: DIV\n"); return DIV; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "rockabilly.l"
{ printf("Token: PLUS\n"); return PLUS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "rockabilly.l"
{ printf("Token: MINUS\n"); return MINUS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "rockabilly.l"
{ printf("Token: NOT\n"); return NOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "rockabilly.l"
{ printf("Token: READ\n"); return READ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "rockabilly.l"
{ printf("Token: ASSIGN\n"); return ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "rockabilly.l"
{
  // if none of the reserved words are found, it is an identifier
  yylval.sval = strdup(yytext);
  printf("Token: IDENTIFIER, Value: %s\n", yylval.sval);
  return IDENTIFIER;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "rockabilly.l"
ECHO;
	YY_BREAK
#line 1354 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 495 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 495 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 494);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 97 "rockabilly.l"


int yywrap() {
  return 1;
}
